<a href="https://colab.research.google.com/github/unknown-shot/Pytorch-30-days/blob/main/01_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

From Resources :

- https://www.youtube.com/watch?v=bQ1SfS4urEA&list=PLmp4AHm0u1g30Sk_9ftX-FMKX5e6x9TBr

fundamental data structures that we used to hold data that we operate on using pytorch are tensors

wait what are tensors ?

tenors are multidimensional arrays 

In [ ]:
import torch
torch.__version__

'1.8.1+cu101'

In [ ]:
# by default the data type that pytorch assumes your data is represented in is torch.float32
torch.get_default_dtype()

torch.float32

> lets say we want our tensors to be created with a different default type

In [ ]:
torch.set_default_dtype(torch.int)
torch.get_default_dtype()

TypeError: ignored

we got an error !

when we are working in building neural networks and on machine learning models we typically work with floating points which is why *only floating point types* are suppported as default dtype in pytorch . we can change to float64 

In [ ]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

see this page [A list of all Tensor types supported by pytorch](https://pytorch.org/docs/stable/tensors.html) 

In [ ]:
list_1 = [1.0 ,2.5 ,8.4 ,9.5]
list_1[2]

8.4

In [ ]:
tensor_1 = torch.rand([2,3,4])
tensor_1

tensor([[[0.2621, 0.3937, 0.0031, 0.9344],
         [0.1719, 0.5858, 0.5375, 0.0040],
         [0.6518, 0.2793, 0.2281, 0.5322]],

        [[0.4793, 0.3545, 0.5726, 0.2871],
         [0.5486, 0.9611, 0.6022, 0.4599],
         [0.7968, 0.1879, 0.7652, 0.5077]]])

In [ ]:
tensor_1[:,1,0:2]

tensor([[0.1719, 0.5858],
        [0.5486, 0.9611]])

## Initializing a Tensor

In [ ]:
# from data

data = [
        [
         [1,2,3],
         [2,3,4]
         ],
        [
         [6,4,2],
         [4,3,7]
        ]
]



# Most commmon Types of Tensors 

In [ ]:
# data types
# 32bit floating point
data = torch.FloatTensor([2,4,6])
data

tensor([2., 4., 6.], dtype=torch.float32)

In [ ]:
# torch.Tensor is An alias for the default tensor type generally default is torch.FloatTensor() but here we changed it as we can see adove
data = torch.Tensor([2,4,5])
data


tensor([2., 4., 5.])

In [ ]:
# as we set the default data type to be torch.float64 , so that will be the type of the tensor that will be created
data.type()

'torch.DoubleTensor'

In [ ]:
# numel returns the totla no.of elements in the input tensor
torch.numel(data)

3

In [ ]:
tensor_uninitialized = torch.Tensor(2,3,4)
tensor_uninitialized

tensor([[[4.6810e-310,  0.0000e+00, 4.9407e-324,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, 4.6810e-310,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00, 4.9407e-324,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [4.9407e-324, 5.4111e-312, 2.1220e-314, 1.0119e-319]]])

when we specify torch.tensor and we only indicate the share of the tensor , the resulting tensor object will be uninitialized i.e behind scenes it allocate memory for this tensor 

there are some handy functions in pytorch

In [ ]:
# this the quick and easy way to initialize the weights of your model parameters
tensor_initialized = torch.rand(2,3)
tensor_initialized

tensor([[0.3971, 0.3544, 0.1847],
        [0.2342, 0.8532, 0.6372]])

lets say we want to create tensor with another dtype


```
torch.tensor().type(torch.IntTensor)
```
